#!/bin/sh

# ddnsto package made by xiaobao
# package maintained at http://www.ddnsto.com

PKGNAME="ddnsto"
PKGPATH="/var/packages/${PKGNAME}"

BINPKG=`ls -l ${PKGPATH}/target | awk -F "-> " '{print $2}'`

BINPATH="bin"
BINFILE="ddnsto"

BINSTART=${BINPKG}/${BINPATH}/${BINFILE}
WHO=`whoami`

case $1 in
  start)
    echo "${WHO} Starting ddnsto ${BINSTART} ..." >> /tmp/ddnsto.log
		${BINSTART} >/tmp/ddnsto.log 2>&1 &
    exit 0
  ;;
  stop)
    echo "Stopping ddnsto ..."
    killall ${BINFILE}
    rm -f /tmp/.ddnsto.pid
    rm -f /tmp/.ddnsto.status
    rm -f /tmp/.ddnsto.up
    exit 0
  ;;
  status)
    pidof ${BINFILE} > /dev/null
    if [ $? -ne 0 ]; then
      echo "Status: ddnsto is not running"
      exit 1
    fi
    echo "Status: ddnsto is running"
    exit 0
  ;;
    log)
        echo ${BINPKG}/${BINPATH}/${BINLOG}
    ;;
esac
